services:
  postgres:
    image: postgres:17-alpine
    container_name: crud-postgres
    environment:
      POSTGRES_DB: cruddb
      POSTGRES_USER: crud
      POSTGRES_PASSWORD: crud
    ports:
      - "5432:5432"
    volumes:
      - crud-postgres-data:/var/lib/postgresql/data

volumes:
  crud-postgres-data: