spring:
  application:
    name: crud

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cruddb}
    username: ${SPRING_DATASOURCE_USERNAME:crud}
    password: ${SPRING_DATASOURCE_PASSWORD:crud}

  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: public
    default-schema: public

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha